name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # TODO(adam): windows-latest
        version: [stable, oldstable]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Check
      env:
        COVER_THRESHOLD: 85.0
      run: make check

    - name: Tests
      run: make test
